/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Homepage extends javax.swing.JFrame {

    static String loginid;

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnregistration = new javax.swing.JMenuItem();
        btnOPD = new javax.swing.JMenuItem();
        btninpatient = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btndoctor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnuser = new javax.swing.JMenuItem();
        btnchanneling = new javax.swing.JMenuItem();
        btnlaboratory = new javax.swing.JMenuItem();
        btnbil = new javax.swing.JMenu();
        btnbill = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Green Memorial Hospital, Manipay");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 550, 280));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 500));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("Patient");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnregistration.setText("Registration");
        btnregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrationActionPerformed(evt);
            }
        });
        jMenu1.add(btnregistration);

        btnOPD.setText("Out Patient");
        btnOPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOPDActionPerformed(evt);
            }
        });
        jMenu1.add(btnOPD);

        btninpatient.setText("In_Patient");
        btninpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninpatientActionPerformed(evt);
            }
        });
        jMenu1.add(btninpatient);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Doctor");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btndoctor.setText("Doctor details");
        btndoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorActionPerformed(evt);
            }
        });
        jMenu2.add(btndoctor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Other");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnuser.setText("User details");
        jMenu3.add(btnuser);

        btnchanneling.setText("Channeling");
        btnchanneling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchannelingActionPerformed(evt);
            }
        });
        jMenu3.add(btnchanneling);

        btnlaboratory.setText("Laboratory");
        btnlaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaboratoryActionPerformed(evt);
            }
        });
        jMenu3.add(btnlaboratory);

        jMenuBar1.add(jMenu3);

        btnbil.setText("Bill");
        btnbil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnbill.setText("Bills");
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });
        btnbil.add(btnbill);

        jMenuBar1.add(btnbil);

        jMenu5.setText("Report");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu6.setText("About Us");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrationActionPerformed
        // TODO add your handling code here:
        new Patientregistration().setVisible(true);
                  this.dispose();
    }//GEN-LAST:event_btnregistrationActionPerformed

    private void btnchannelingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchannelingActionPerformed
         new Channelingform().setVisible(true);
                  this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnchannelingActionPerformed

    private void btnOPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOPDActionPerformed
       new OPD().setVisible(true);
                  this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnOPDActionPerformed

    private void btninpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninpatientActionPerformed
       new Inpatientregistration().setVisible(true);
                  this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_btninpatientActionPerformed

    private void btndoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorActionPerformed
        // TODO add your handling code here:
        new Doctor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndoctorActionPerformed

    private void btnlaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaboratoryActionPerformed
        // TODO add your handling code here:
        new Labservice().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlaboratoryActionPerformed

    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        // TODO add your handling code here:
        new Bills().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Homepage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnOPD;
    private javax.swing.JMenu btnbil;
    private javax.swing.JMenuItem btnbill;
    private javax.swing.JMenuItem btnchanneling;
    private javax.swing.JMenuItem btndoctor;
    private javax.swing.JMenuItem btninpatient;
    private javax.swing.JMenuItem btnlaboratory;
    private javax.swing.JMenuItem btnregistration;
    private javax.swing.JMenuItem btnuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
